### PR TITLE
Logistic Regression - Pykokkos example

### PR DESCRIPTION
**Pull request by ShahzadUmair**
This PR contains the basic working scikit learn's version of logistic regression.

We havent worked on the nested functions in this PR e.g. `sklearn.utils.validation.check_is_fitted` and a few others. As of now we just convert the output of these functions from numpy to pykokkos using `asarray`.

I am working on figuring out if we can get any significant gains from copying scikit learns internal functions and making them compatible with pykokkos.

This PR also fixes the mypy version to `0.981` because in the latest version mypy is testing some files which are in the ignore list (also pointed out [here](https://github.com/kokkos/pykokkos/pull/128#issuecomment-1326718976)).

### CODE REVIEW

**Comment by JBludau** [comment]
this looks a little large to be reviewed ... is the `LR.py` copied from somewhere? If so we should mark it as such to give credit where it is due

**Comment by NaderAlAwar** [comment]
Yeah it's the scikit-learn implementation of logistic regression using the pykokkos ufuncs. @ShahzadUmair could you please add the license information like we did for naive bayes? I'll review this shortly

**Review by NaderAlAwar — CHANGES_REQUESTED** [review]
Minor change needed

**Comment by tylerjereddy** [comment]
I don't think the `mypy` pin should have been needed since gh-129 was merged first.

**Pull request merged**
